# Generated by Django 3.2.7 on 2021-10-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('birthdate', models.DateField(verbose_name='yyyy-mm-dd')),
            ],
        ),
    ]
