# Generated by Django 3.2.7 on 2021-10-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='birthdate',
            new_name='Birthdate',
        ),
    ]
