# Generated by Django 3.2.7 on 2021-10-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_rename_birthdate_data_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Birthdate',
            field=models.DateField(verbose_name='YYYY-MM-DD'),
        ),
    ]
