# Generated by Django 3.2.7 on 2021-10-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_data_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='')),
                ('age', models.IntegerField(default='18')),
                ('father', models.CharField(max_length=20)),
                ('Birthdate', models.CharField(default='', max_length=30)),
                ('collage', models.CharField(default='', max_length=30)),
                ('dataid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.data')),
            ],
        ),
    ]
